---

language: node_js
node_js:
  - node

script:
  - make lint
  - make test

notifications:
  email:
    - avdeev2033@icloud.com
  on_success: never # default: change
  on_failure: always # default: always
